### ISSUE TITLE
The mux signals are inversely sorted

### ISSUE THREAD

**Issue by MarekPio** [cantools/cantools#377]
The mux signals are inversely sorted each time the file is saved (or loaded). Version: cantools 36.4.0

` SG_ Humidity6 m6 : 9|7@1+ (1,0) [0|100] "%" Vector__XXX
 SG_ Humidity5 m5 : 9|7@1+ (1,0) [0|100] "%" Vector__XXX
 SG_ Humidity4 m4 : 9|7@1+ (1,0) [0|100] "%" Vector__XXX
 SG_ Humidity3 m3 : 9|7@1+ (1,0) [0|100] "%" Vector__XXX
 SG_ Humidity2 m2 : 9|7@1+ (1,0) [0|100] "%" Vector__XXX
 SG_ Humidity1 m1 : 9|7@1+ (1,0) [0|100] "%" Vector__XXX`
 
 saves as
 
 ` SG_ Humidity1 m1 : 9|7@1+ (1,0) [0|100] "%" Vector__XXX
 SG_ Humidity2 m2 : 9|7@1+ (1,0) [0|100] "%" Vector__XXX
 SG_ Humidity3 m3 : 9|7@1+ (1,0) [0|100] "%" Vector__XXX
 SG_ Humidity4 m4 : 9|7@1+ (1,0) [0|100] "%" Vector__XXX
 SG_ Humidity5 m5 : 9|7@1+ (1,0) [0|100] "%" Vector__XXX
 SG_ Humidity6 m6 : 9|7@1+ (1,0) [0|100] "%" Vector__XXX`

To solve this issue save the dbc two times

`    ''' Save database to file '''
    cantools.database.dump_file(dbc, "temp.dbc")
    ''' Second load to prevent changing signals with mux '''
    dbc = cantools.database.load_file("temp.dbc")
    os.remove("temp.dbc")
    ''' Save database to file '''
    cantools.database.dump_file(dbc, out_dbc_file)`

It is important to keep SVN / Git commits clean.

**Comment by erzoe** [comment]
Since version 37.0.3 `cantools.database.load_file` and `cantools.database.dump_file` have a paramter to control whether and how signals are sorted.

If you don't want the signals to be sorted use `sort_signals=None`.

If you want the signals to be sorted you can use something like `sort_signals = lambda signals: list(sorted(signals, key=lambda sig: (sig.start, sig.multiplexer_ids[0] if sig.multiplexer_ids else 0)))`.

By default signals are sorted by their start bit in `cantools.database.load_file` (in the constructor of Message to be more precise). In the case of multiplexing several signals can have the same start bit and their order is undefined. It might be a good idea to change that.

In `cantools.database.dump_file` the default depends on the file format. For dbc files the default is to sort the signals by start bit in reverse order.

Since version 37.0.3 this is documented in `help(cantools.database.load_string)` and `help(cantools.database.dump_file)`.
