### ISSUE TITLE
Enable Floats in C Source Generation

### ISSUE THREAD

**Issue by samc1213** [cantools/cantools#393]
Right now, `generate_c_source` only generates encode and decode functions with `double`s. Some floating point units may only have hardware support for single precision, so it might be nice to enable a flag like `generate_c_source --use-float`, which would use `float` instead of double.

@juleq Does this proposal make sense or do you forsee any issue? I'm happy to implement if you think this would be a worthwhile change.

**Comment by juleq** [comment]
Disclaimer: I have not used the feature (yet).

I assume it has been selected to output double because no/little concerns with respect to precision loss should arise for having double all the way.

Since even a lot of modern lower- to mid-end MCUs do have no or just an SP FPU, I think the option would be appreciated. And it also helps when you have strong size constraints.

If you choose to give it a shot, do not forget the f postfix on constants to prevent unwanted double promotion.

**Comment by samc1213** [comment]
Sounds good, I will take a stab at it. My MCU just has an SP MCU, and DP operations are implemented in software / with more instructions. Good call on the f postfix, thank you.

**Comment by timbitss** [comment]
I was about to make the same issue last week! I created a [fork](https://github.com/timbitss/cantools/commit/a4b3c9390f3c71cd17dd76444a60fb2ac6a4ffb5) just to convert doubles to floats for factors other than 1. A flag option would be nice. Hope to see this resolved soon

**Comment by samc1213** [comment]
@timbitss if you have time, please install the version in #394 and see if it works with your project/system. Please let me know your thoughts.
