### ISSUE TITLE
Error decoding message containing signals of odd length

### ISSUE THREAD

**Issue by manutoky** [cantools/cantools#447]
We have signals inside a CAN FD message of length 11 bits. Decoding these signals gives the following error:
bitstruct.Error: expected float size of 16, 32, or 64 bits (got 11)

Any work-around possible?

**Comment by andlaus** [comment]
the problem is not that the signal is 11 bits long, but that it is declared as an IEEE 754 floating point value (which is only defined for 16, 32, 64, 128 and 256 bits and in cantools we limit ourselves to 16, 32 and 64 bits). What you probably have is an integer with a scaling factor and offset attached (this will work fine with cantools)...
